sudo: required
language: generic

services:
  - docker

before_install: 
  - docker build -t gidonco/react-test -f ./client/Dockerfile.dev ./client

script: 
    - docker  run -e CI=true gidonco/react-test npm test

after_success: 
    - docker build -t gidonco/multi-client ./client
    - docker build -t gidonco/multi-nginx ./nginx
    - docker build -t gidonco/multi-server ./server
    - docker build -t gidonco/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u  "$DOCKER_ID" --password-stdin
    - docker push gidonco/multi-client
    - docker push gidonco/multi-nginx
    - docker push gidonco/multi-server
    - docker push gidonco/multi-worker